# Generated by Django 4.1.7 on 2023-08-31 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('state', models.BooleanField(default=True)),
                ('user', models.ForeignKey(max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=50)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True, null=True)),
                ('location', models.CharField(max_length=150, null=True)),
                ('date_finished', models.DateTimeField(null=True)),
                ('deadline', models.DateTimeField(null=True)),
                ('icon', models.CharField(max_length=25, null=True)),
                ('priority', models.CharField(default='Baja', max_length=250)),
                ('state', models.BooleanField(default=True)),
                ('files', models.FileField(blank=True, null=True, upload_to='uploads/tasks')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.category')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.status')),
                ('user', models.ForeignKey(max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('content', models.CharField(max_length=1000, null=True)),
                ('date_finished', models.DateTimeField(null=True)),
                ('deadline', models.DateTimeField(null=True)),
                ('priority', models.CharField(max_length=250)),
                ('state', models.BooleanField(default=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='todo.task')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=150)),
                ('type_notification', models.CharField(max_length=100)),
                ('state', models.BooleanField(default=True)),
                ('is_readead', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000, null=True)),
                ('tags', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=500)),
                ('files', models.FileField(blank=True, null=True, upload_to='uploads/notes')),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
