# Generated by Django 4.1.7 on 2023-06-08 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_category_status_task_date_finished_task_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
