# Generated by Django 4.1.7 on 2023-06-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_task_status_alter_task_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='uploads/notes'),
        ),
        migrations.AlterField(
            model_name='task',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='uploads/tasks'),
        ),
    ]
